version: 2
jobs:
  python38:
    docker:
      - image: circleci/python:3.8
      - image: rabbitmq:3.7
      - image: memcached:1.5
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
        environment:
          discovery.type: single-node
          ES_JAVA_OPTS: -Xms512m -Xmx512m
      - image: mysql:5.7
        environment:
          MYSQL_USER: airone
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: airone
        command: [--character-set-server=utf8, --collation-server=utf8_general_ci, --default-storage-engine=innodb]
    environment:
      TOXENV: "py38"
    steps:
      - checkout
      - run:
          name: Wait for ElasticSearch
          command: dockerize -wait tcp://127.0.0.1:9200 -timeout 120s
      - restore_cache:
          key: py38-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}
      - run:
          name: Install tox coverage
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox coverage
      - run:
          name: Wait for MySQL is available
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Grant permission for airone user to be able to manipulate multiple databases (airone and test_airone)
          command: |
            sudo apt-get update
            sudo apt-get install -y default-mysql-client
            mysql -uroot -h127.0.0.1 -ppassword -e "GRANT ALL ON *.* to airone@'%' IDENTIFIED BY 'password'"
      - run:
          name: Testing
          command: |
            . venv/bin/activate
            tox
      - save_cache:
          key: py38-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}
          paths:
            - venv
            - .tox/py38

  python36:
    docker:
      - image: circleci/python:3.6
      - image: rabbitmq:3.7
      - image: memcached:1.5
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
        environment:
          discovery.type: single-node
          ES_JAVA_OPTS: -Xms512m -Xmx512m
      - image: mysql:5.7
        environment:
          MYSQL_USER: airone
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: airone
        command: [--character-set-server=utf8, --collation-server=utf8_general_ci, --default-storage-engine=innodb]
    environment:
      TOXENV: "py36"
    steps:
      - checkout
      - run:
          name: Wait for ElasticSearch
          command: dockerize -wait tcp://127.0.0.1:9200 -timeout 120s
      - restore_cache:
          key: py36-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}
      - run:
          name: Install tox coverage
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox coverage
      - run:
          name: Wait for MySQL is available
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Grant permission for airone user to be able to manipulate multiple databases (airone and test_airone)
          command: |
            sudo apt-get update
            sudo apt-get install -y default-mysql-client
            mysql -uroot -h127.0.0.1 -ppassword -e "GRANT ALL ON *.* to airone@'%' IDENTIFIED BY 'password'"
      - run:
          name: Testing
          command: |
            . venv/bin/activate
            tox
      - save_cache:
          key: py36-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}
          paths:
            - venv
            - .tox/py36

  python35:
    docker:
      - image: circleci/python:3.5
      - image: rabbitmq:3.7
      - image: memcached:1.5
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
        environment:
          discovery.type: single-node
          ES_JAVA_OPTS: -Xms512m -Xmx512m
      - image: mysql:5.7
        environment:
          MYSQL_USER: airone
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: airone
        command: [--character-set-server=utf8, --collation-server=utf8_general_ci, --default-storage-engine=innodb]
    environment:
      TOXENV: "py35"
    steps:
      - checkout
      - run:
          name: Wait for ElasticSearch
          command: dockerize -wait tcp://127.0.0.1:9200 -timeout 120s
      - restore_cache:
          key: py35-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}
      - run:
          name: Install tox tox-pyenv coverage
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox coverage
      - run:
          name: Wait for MySQL is available
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Grant permission for airone user to be able to manipulate multiple databases (airone and test_airone)
          command: |
            sudo apt-get update
            sudo apt-get install -y default-mysql-client
            mysql -uroot -h127.0.0.1 -ppassword -e "GRANT ALL ON *.* to airone@'%' IDENTIFIED BY 'password'"
      - run:
          name: Testing
          command: |
            . venv/bin/activate
            tox
      - save_cache:
          key: py35-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}
          paths:
            - venv
            - .tox/py35
      - run:
          name: Coverage
          command: |
            . venv/bin/activate
            ./coverage.sh

  pep8:
    docker:
      - image: circleci/python:3.5
    environment:
      TOXENV: "pep8"
    steps:
      - checkout
      - run:
          name: Install tox tox-pyenv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox
      - run:
          name: flake8
          command: |
            . venv/bin/activate
            tox

workflows:
  version: 2
  build_and_test:
    jobs:
      - python38
      - python36
      - python35
      - pep8
